### ISSUE TITLE
Configurable Piece Colors

### ISSUE THREAD

**Issue by bwiggs** [THeK3nger/obsidian-chessboard#10]
It'd be great if we could customize the colors of the pieces, similar to how we can customize the board. I have a dark obsidian theme, and have made the board dark to match, but now the black pieces blend into the board colors, and the white pieces have too much contrast.

![CleanShot 2024-09-04 at 22 43 27](https://github.com/user-attachments/assets/54c3972e-388b-4da4-b503-d40ec7dd46a7)

**Comment by THeK3nger** [comment]
I am working on it. 
![CleanShot 2024-09-10 at 15 49 28@2x](https://github.com/user-attachments/assets/ca3ebeb5-7304-42ac-83bf-e686a7c5f8f7)

I'll take the chance to use a better color selection interface in the settings. It is a long time due.

**Comment by bwiggs** [comment]
Thank you, much better!
