### ISSUE TITLE
Feature Request: Set board orientation

### ISSUE THREAD

**Issue by QueenLatifa** [THeK3nger/obsidian-chessboard#2]
Hi, first of all, great work with the app. Keep it up!

Could I request the ability to flip the board with a setting the code block?

Let me know if there already such a setting and I've missed it. Thanks so much.

**Comment by THeK3nger** [comment]
Hi!

Actually, yes. You can. I just updated the README (I don't remember because I haven't done it before 😄).

You can use the `orientation` command. It can be `white` (default) or `black`.

### Example

````
```chessboard
fen: r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R
orientation: black
```
````

**Comment by QueenLatifa** [comment]
That's perfect. Thank you
